apiVersion: v1
kind: Service
metadata:
  name: dd-agent
spec:
  ports:
  - name: dd-port
    port: 8125
    targetPort: 8125
    protocol: UDP
  selector:
    app: dd-agent

---

apiVersion: v1
kind: ReplicationController
metadata:
  name: dd-agent
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dd-agent
    spec:
      containers:
        - name: datadog
          image: nicovillanueva/dd-agent-kong:latest
          env:
            - name: API_KEY
              value: <__NOPE__>
            - name: POSTGRES_DB
              value: kong
          ports:
            - containerPort: 8125
